name: 自动部署

on:
  push:
    branches:
      - dev

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: npm install --save

      - name: 打包项目
        run: npm run build

      # 将构建后的文件部署到 gh-pages 分支
      - name: 部署到githubpage
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: preview
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
