name: 自动部署

on:
  push:
    branches:
      - dev

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: npm install --save

      - name: 打包项目
        run: npm run build

      # 部署到 GitHub Pages
      - name: 部署到github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
