name: 自动部署

on:
  push:
    branches:
      - dev

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install Dependencies
        run: bundle install

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: 安装pnpm
        run: npm install pnpm -g

      - name: 安装依赖
        run: pnpm install --save

      - name: 打包项目
        run: pnpm build
